# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: odoh-proxy-go-sls
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  stage: prod
  timeout: 10
  region: ap-northeast-1
  endpointType: regional
  apiGateway:
    binaryMediaTypes:
      - 'application/oblivious-dns-message'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  query:
    handler: bin/proxy
    events:
      - http:
          path: dns-query
          method: post
      - http:
          path: proxy
          method: post

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "dns-proxy.kenit.me"
    basePath: ''
    stage: prod
    createRoute53Record: true
    certificateName: "*.kenit.me"
    endpointType: 'regional'